### ISSUE TITLE
It seems to work well on Windows!

### ISSUE THREAD

**Issue by mkasprz** [griffin-stewie/vscode-selectword#1]
Hi!
I just wanted to let You know that the extension seems to work well on Windows. I'm not sure if it works perfectly, but I do not really see any reason why it shouldn't.
Thank You for creating it by the way! I use it with https://marketplace.visualstudio.com/items?itemName=colch.quick-open-prefill-selection and https://marketplace.visualstudio.com/items?itemName=geddski.macros and it does a work quite nicely.

**Comment by griffin-stewie** [comment]
@mkasprz 
Thank you for your information!

My extension `vscode-selectword` is only using official API and no external dependencies, so maybe works on Windows. Reason that I don't support windows are I don't have any Windows and Linux machines and I had some problem about it Atom Extensions that I made.

Anyway, I love extensions that you mentioned, especially [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros)!
